---
abstract: 'the frequency count of strings'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CountString
provides:
  Text::CountString:
    file: lib/Text/CountString.pm
    version: 0.01
requires:
  Exporter: 0
  parent: 0
  perl: 5.008001
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: http://github.com/bayashi/Text-CountString/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Text-CountString
version: 0.01
